In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.dtype
arr.astype(np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [3]:
zeros_arr = np.zeros((5,5))
zeros_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
ones_arr = np.ones((5,5))
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
arr = np.arange(0,99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [6]:
arr = np.arange(0,99,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
arr = np.arange(0,100).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
eye_arr = np.eye(10,10)
eye_arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Create Random  Array

In [9]:
arr = np.random.randn(5,5)
arr

array([[ 0.47646601,  1.90226679, -0.47313931, -0.21045941,  0.5571158 ],
       [-0.48810677, -2.05340141,  0.5753781 ,  0.27662657,  0.07125215],
       [-0.10682424, -2.16087219, -0.12709794,  0.81658322,  0.4656924 ],
       [ 0.0967734 ,  0.95678392,  1.07747647,  0.21527322,  0.76472994],
       [ 0.37087202, -0.16456942,  1.64406207, -1.09699924, -0.31350598]])

In [10]:
arr_gauss = np.random.normal(loc=0.0, scale=1, size = (5,5))
arr_gauss

array([[ 0.67285292, -1.21751798, -0.41384873,  0.65290101,  0.80714097],
       [-0.01235664,  0.15828052,  0.05796977, -0.08441754,  0.14766046],
       [ 1.27936073,  0.98252492,  0.40998268,  0.42755181, -0.00887737],
       [ 0.11381309, -0.79933821, -1.49143107,  0.13359502,  0.06026706],
       [-0.64262725, -1.43537312,  0.13506455, -1.21109103,  1.14088083]])

In [11]:
arr_uniform = np.random.uniform(low=-3,high=3, size = (5,5))
arr_uniform

array([[-1.64333205,  1.45614031,  0.12588218,  0.69137069, -1.51791405],
       [-2.77776739,  2.96361724,  0.12431975, -1.6672629 , -1.11638234],
       [ 1.20257961, -1.63711486, -0.46187189, -1.41730519,  0.13198546],
       [ 2.19253444,  2.92397594, -1.06300518,  0.53059122,  2.60194764],
       [ 1.85731154, -2.77797332, -1.78482879,  1.41426211,  1.35884937]])

In [12]:
arr_int = np.random.randint(low = -3, high=3, size = (4,4))
arr_int

array([[-2,  1,  1,  1],
       [-1,  2, -1,  1],
       [ 2,  0,  0,  2],
       [ 0, -2,  0,  1]])

# Read, load and save numpy file


In [17]:
np.save('./arr.npy',arr)
np.savetxt('arr.txt ', arr)
np.load('./arr.npy')

array([[ 0.47646601,  1.90226679, -0.47313931, -0.21045941,  0.5571158 ],
       [-0.48810677, -2.05340141,  0.5753781 ,  0.27662657,  0.07125215],
       [-0.10682424, -2.16087219, -0.12709794,  0.81658322,  0.4656924 ],
       [ 0.0967734 ,  0.95678392,  1.07747647,  0.21527322,  0.76472994],
       [ 0.37087202, -0.16456942,  1.64406207, -1.09699924, -0.31350598]])

# Frobenious Norm


In [18]:
A = np.array([[1, 4, 2],
              [3, 2, 1],
              [4, 6, 7]])
np.linalg.norm(A, ord='fro')

11.661903789690601

In [24]:
A = np.array([[1, 4, 2],
              [3, 2, 1],
              [4, 6, 7]])

B = np.array([[0, 3, 4],
              [3, 4, 2],
              [4, 6, 8]])

#add matrix
Sum = A+B
# multi matrix
Mul = A.dot(B)
#element-wise product
EWS = A*B
#trace
A_trace = np.trace(A)
#determinant
det_A =np.linalg.det(A)
#rank
rank = np.linalg.matrix_rank(A)
#pseudo-inverse of a matrix
A_inv = np.linalg.pinv(A)
#Transpose matrix
AT = A.T


# Concatenate và Stack

In [25]:
A = np.random.randint(0, 255, size=(28, 28, 3))
B = np.random.randint(0, 255, size=(28, 28, 3))

AB = np.concatenate((A, B), axis=1)
np.stack([A, B])
np.vstack([A, B])
np.hstack([A, B])
B = np.expand_dims(B, axis=-1)

# min, max, mean, sum, argmax, argmin

In [29]:
arr = np.random.randn(5,5)
min = np.min(arr,axis = 0)
max = np.max(arr, axis = 1)
mean = np.mean(arr,axis=0)
sum = np.sum(arr,axis = 1)
argmax = np.argmax(arr,axis = 1)
argmin = np.argmax(arr, axis =0)


In [71]:
def relu(x):
  out=x.copy()
  out[out<0] = 0
  return out
  
def sigmoid(X):
  out = 1/(1+np.exp(-X))
  return out
def tanh(X):
  out = (np.exp(X)-np.exp(-X))/(np.exp(X)+np.exp(-X))
  return out
def softmax(X):
  E = np.exp(X)
  P = E/np.sum(E)
  out = np.sum(P,axis = 1,keepdims=True)
  return out
def softmax_(x):
    max_x = np.exp(x-np.max(x, axis=1, keepdims=True))
    probs = max_x/np.sum(max_x,axis =1,keepdims=True)
    return probs 


In [73]:
X = np.array([[-2,-9,0,2],[1,2,3,4],[4,3,3,1],[6,6,9,9]])

In [77]:
softmax_(X)

array([[1.58760101e-02, 1.44770473e-05, 1.17308730e-01, 8.66800783e-01],
       [3.20586033e-02, 8.71443187e-02, 2.36882818e-01, 6.43914260e-01],
       [5.60052795e-01, 2.06031909e-01, 2.06031909e-01, 2.78833868e-02],
       [2.37129366e-02, 2.37129366e-02, 4.76287063e-01, 4.76287063e-01]])

In [91]:
sigmoid(X).max(axis=1)

array([0.88079708, 0.98201379, 0.98201379, 0.99987661])

In [92]:
tanh(X).max(axis=1)

array([0.96402758, 0.9993293 , 0.9993293 , 0.99999997])

In [93]:
relu(X)

array([[0, 0, 0, 2],
       [1, 2, 3, 4],
       [4, 3, 3, 1],
       [6, 6, 9, 9]])